[config]
path = "/mirror/aosc-os"
retro_arches = ["alpha", "armv4", "armv6hf", "armv7hf", "i486", "loongson2f", "m68k", "powerpc", "ppc64", "sparc64"]

[bulletin]
type = "info"
title = "Thank You for Choosing AOSC OS"
title-tr = "bulletin-title"
body = "AOSC OS strives to simplify your user experience and improve your day-to-day productivity."
body-tr = "bulletin-body"

[[mirrors]]
name = "Alibaba Cloud Open Source Mirror"
name-tr = "aliyun-name"
url = "https://mirrors.aliyun.com/anthon/aosc-os/"
loc = "China"
loc-tr = "aliyun-loc"

[[mirrors]]
name = "Beijing Foreign Studies University Open Source Mirror"
name-tr = "bfsu-name"
url = "https://mirrors.bfsu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "bfsu-loc"

[[mirrors]]
name = "GeekPie (ShanghaiTech University) Open Source Mirror"
name-tr = "geekpie-name"
url = "https://mirrors.shanghaitech.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "geekpie-loc"

[[mirrors]]
name = "HIT Open Source Mirror"
name-tr = "hit-name"
url = "https://mirror.hit.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "hit-loc"

[[mirrors]]
name = "ISCAS Open Source Mirror"
name-tr = "iscas-name"
url = "https://mirror.iscas.ac.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "iscas-loc"

[[mirrors]]
name = "Jilin University Open Source Mirror"
name-tr = "jlu-name"
url = "http://mirrors.jlu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "jlu-loc"

[[mirrors]]
name = "LZUOSS Open Source Mirror"
name-tr = "lzu-name"
url = "https://mirror.lzu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "lzu-loc"

[[mirrors]]
name = "Nanyang Institute of Technology Open Source Mirror (CIPS)"
name-tr = "nit-name"
url = "https://mirror.nyist.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "nit-loc"

[[mirrors]]
name = "NJU Mirror (Nanjing University)"
name-tr = "nju-name"
url = "https://mirror.nju.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "nju-loc"

[[mirrors]]
name = "SDU Mirrors (Shandong University)"
name-tr = "sdu-name"
url = "https://mirrors.sdu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "sdu-loc"

[[mirrors]]
name = "SJTUG Mirror (Shanghai Jiao Tong University)"
name-tr = "sjtug-name"
url = "https://mirror.sjtu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "sjtug-loc"

[[mirrors]]
name = "Tencent Open Source Software Mirror"
name-tr = "tencent-name"
url = "https://mirrors.cloud.tencent.com/anthon/aosc-os/"
loc = "China"
loc-tr = "tencent-loc"

[[mirrors]]
name = "Tsukuba WIDE Public Mirror service"
name-tr = "tsukuba-name"
url = "http://ftp.tsukuba.wide.ad.jp/Linux/anthon/aosc-os/"
loc = "Japan"
loc-tr = "tsukuba-loc"

[[mirrors]]
name = "Tsinghua Open Source Mirror (TUNA)"
name-tr = "tuna-name"
url = "https://mirrors.tuna.tsinghua.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "tuna-loc"

[[mirrors]]
name = "USTC Open Source Software Mirror"
name-tr = "ustc-name"
url = "https://mirrors.ustc.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "ustc-loc"

[[mirrors]]
name = "Netherlands Local Unix User Group (NLUUG) OSS Mirror"
name-tr = "nluug-name"
url = "https://ftp.nluug.nl/os/Linux/distr/anthon/aosc-os/"
loc = "Europe"
loc-tr = "nluug-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Estonia)"
name-tr = "xtom-ee-name"
url = "https://mirror.xtom.ee/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-ee-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Germany)"
name-tr = "xtom-de-name"
url = "https://mirror.xtom.de/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-de-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Netherlands)"
name-tr = "xtom-nl-name"
url = "https://mirror.xtom.nl/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-nl-loc"

[[mirrors]]
name = "KoDDoS HK"
name-tr = "koddos-hk-name"
url = "https://mirror-hk.koddos.net/anthon/aosc-os/"
loc = "Hong Kong"
loc-tr = "koddos-hk-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Hong Kong)"
name-tr = "xtom-hk-name"
url = "https://mirror.xtom.com.hk/anthon/aosc-os/"
loc = "Hong Kong"
loc-tr = "xtom-hk-loc"

[[mirrors]]
name = "Fastly CDN"
name-tr = "fastly-name"
url = "https://aosc-repo.freetls.fastly.net/aosc-os/"
loc = "Worldwide"
loc-tr = "fastly-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror"
name-tr = "xtom-name"
url = "https://mirror.xtom.com/anthon/aosc-os/"
loc = "Worldwide"
loc-tr = "xtom-loc"

[distro.mainline.desktop]
name = "Desktop"
name-tr = "desktop-name"
description = "A full-featured desktop experience."
description-tr = "desktop-description"

[distro.mainline."desktop+nvidia"]
name = "Desktop (with NVIDIA driver)"
name-tr = "desktop+nvidia-name"
description = "A full-featured desktop experience (with proprietary NVIDIA driver)."
description-tr = "desktop+nvidia-description"

[distro.mainline.base]
name = "Base"
name-tr = "base-name"
description = "A minimal system with a basic set of utilities."
description-tr = "base-description"

[distro.mainline.buildkit]
name = "BuildKit"
name-tr = "buildkit-name"
description = "A standardized development environment."
description-tr = "buildkit-description"

[distro.mainline.container]
name = "Container"
name-tr = "container-name"
description = "A minimal system for containers."
description-tr = "container-description"

[distro.mainline.server]
name = "Server"
name-tr = "server-name"
description = "A full-featured system for personal servers."
description-tr = "server-description"

[distro.mainline.wsl]
name = "WSL"
name-tr = "wsl-name"
description = "A full-featured system for Windows Subsystem for Linux."
description-tr = "wsl-description"

[distro.retro.desktop]
name = "Desktop"
name-tr = "retro-desktop-name"
description = "A full-featured desktop experience (for legacy devices)."
description-tr = "retro-desktop-description"

[distro.retro.base]
name = "Base"
name-tr = "retro-base-name"
description = "A minimal system with a basic set of utilities (for legacy devices)."
description-tr = "retro-base-description"

[distro.retro.server]
name = "Server"
name-tr = "retro-server-name"
description = "A full-featured system for personal servers (for legacy devices)."
description-tr = "retro-server-description"

[distro.retro.buildkit]
name = "BuildKit"
name-tr = "retro-buildkit-name"
description = "A standardized development environment (for legacy devices)."
description-tr = "retro-buildkit-description"

[distro.retro.container]
name = "Container"
name-tr = "retro-container-name"
description = "A minimal system for containers (for legacy devices)."
description-tr = "retro-container-description"
